### PR TITLE
convert to python3 compatibility (uses six/futurize) and include option for md5 encrypted passwords.

### PR DESCRIPTION
**Pull request by csawyerYumaed**
HI! I needed md5 encrypted passwords for my use case, and so I added it to your library.
we also are in the process of moving our code to work across python2 and python3, so I fixed that up as well.

I probably should have made them 2 different pull requests, but I didn't think about it until after I was done, so you get them in bulk :) sorry.

### CODE REVIEW

**Comment by thesharp** [comment]
Hi @csawyerYumaed!

I will take a look at this tomorrow. Thanks for the PR.

**Comment by csawyerYumaed** [comment]
actually the travis build broke so I'm going to send another that should fix the travis build.

**Comment by csawyerYumaed** [comment]
assuming I can figure it out again :)

**Comment by thesharp** [comment]
Sure, waiting on your fix then. :)

**Comment by csawyerYumaed** [comment]
ok I don't know how.  I tried.  my fork should have the fix for the travis CI fix. (it didn't have the future module in requirements.txt).

**Comment by thesharp** [comment]
Hey @csawyerYumaed it appears that tests for 2.6 version were broken. I've fixed them now, so it'd be nice if you could open a new PR against the current HEAD and close the old one.

Thanks!

**Comment by thesharp** [comment]
Okay, it appears that you don't need to open a new PR against a new HEAD, it applies it automagically.

I've managed to fix your error with running tests, but now I can't manage to run your new tests like at all.

**Comment by thesharp** [comment]
Oh, got that. For some unknown reason you made the ``test_basic.py`` file executable. ``nosetests`` binary skips such tests.

**Comment by thesharp** [comment]
Okay, now we need to figure out what to do with broken 2.6. :)

**Comment by thesharp** [comment]
Well, congratulations, your patch made it into htpasswd-2.3 already available on PyPI.

Thanks for your contribution.

**Comment by csawyerYumaed** [comment]
sorry I made it executable, I didn't realize I did it! I didn't test against py2.6, only 2.7 and 3.4.

**Pull request merged**
